# Generated by Django 5.1.1 on 2024-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_tag_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='scopes', to='articles.tag'),
        ),
    ]
