# Generated by Django 5.1.1 on 2024-10-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
