# Generated by Django 5.1.1 on 2024-10-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
    ]
