# Generated by Django 5.1.1 on 2024-10-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('tag', 'is_main'), name='unique_tag_is_main'),
        ),
    ]
