# Generated by Django 5.1.1 on 2024-10-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_scope_unique_tag_is_main'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('tag', 'is_main'), name='unique_tag_is_main'),
        ),
    ]
